[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "./lib" }
macros = { path = "./macros" }
clap = { version = "4.4.7", features = ["derive"] }
itertools = "0.12.0"
nom = "7.1.3"
num = "0.4.1"
pathfinding = "4.3.3"
inventory = "0.3.21"
